// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuylaxlzoahshctraewp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1eWxheGx6b2Foc2hjdHJhZXdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTI4NTksImV4cCI6MjA2NDUyODg1OX0.3L0Wx7lGm6IO-NvdKmqrFRp-JRi63-HfmRQvearwbBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);